### ISSUE TITLE
Ability to pass nested_scope argument to textstat_polarity

### ISSUE THREAD

**Issue by sebastianmng** [quanteda/quanteda.sentiment#12]
## Requested feature

The function `textstat_polarity` seems to use the default value of "key" of `nested_scope` when it calls `tokens_lookup`. I'd be useful if one  could pass "dictionary" to the `nested_scope` argument of the `tokens_lookup` call in `textstat_polarity`

## Use case

The code below computes a sentiment score of 0 because `tokens_lookup` (with the `nested_scope` default) processes the tokens as `c("The", "settlement","was","NEG_POSITIVE","POSITIVE","."")`, where "NEG_POSITIVE" is assigned to "not amiable" and "POSITIVE" is assigned to "amiable". "NEG_POSITIVE" and "POSITIVE" cancel each other out, which produces the incorrect value of 0. The correct processing for this case is obtained when `nested_scope = "dictionary"` and the tokens are processed as `c("The", "settlement","was","NEG_POSITIVE","."")`.

```r
require(quanteda.sentiment)
toks <- tokens("The settlement was not amiable.")
textstat_polarity(x = toks, 
                  dictionary = data_dictionary_LSD2015,
                  fun = sent_abspropdiff)
```
 doc_id sentiment
1  text1         0

**Comment by kbenoit** [comment]
Good spot, thanks! This was already set for `nested_scope = "dictionary"` in `textstat_valence()`, but I've now changed `textstat_polarity()` to have the same value.

```r
  dict <- dictionary(list(positive = "good", negative = "not good"))
  polarity(dict) <- list(pos = "positive", neg = "negative")
  valence(dict) <- c(positive = 1, negative = -1)
  toks <- tokens("The test is not good")

  textstat_polarity(toks, dictionary = dict, fun = sent_abspropdiff)
  ##   doc_id sentiment
  ## 1  text1     -0.25
```
