### ISSUE TITLE
Sentiment analysis in Spanish

### ISSUE THREAD

**Issue by ManuelSpinola** [quanteda/quanteda.sentiment#14]
Is it possible to use qaunteda.sentiment to do sentiment anaysis in Spanish?

**Comment by kbenoit** [comment]
Yes, but only if you supply a Spanish sentiment dictionary and then add polarities and/or valences. `data_dictionary_Rauh` is in German, for instance. If you wish to supply a Spanish dictionary, we would be glad to include it.
