### ISSUE TITLE
textstat_polarity error

### ISSUE THREAD

**Issue by giuliagrisot** [quanteda/quanteda.sentiment#7]
I just ran this code, which worked perfectly yesterday

```
corpus(corpus_all_entities) %>%
  textstat_polarity(dictionary = data_dictionary_Rauh)
```
 and it is now giving me the error
```
Error in UseMethod("polarity") : no applicable method for 'polarity' applied to an object of class "dictionary3"
```

any ideas why is this happening? has there been an update?

**Comment by maxhuji** [comment]
I run into the same problem. Did you manage to fix it somehow?

**Comment by kbenoit** [comment]
Should be all fixed now.
