### ISSUE TITLE
meta slot error for dictionaries...

### ISSUE THREAD

**Issue by vikram-rawat** [quanteda/quanteda.sentiment#9]
I get an Error on this code...

```
textstat_polarity(
  x = data_corpus_inaugural,
  dictionary = data_dictionary_Rauh)

# Error in polarity.dictionary2(dictionary) : 
# no slot of name "meta" for this object of class "dictionary2"
```
When I checked deeper the code looks like this 

```
get_polarity_dictionary <- function(dictionary) {
  poles <- polarity(dictionary)
  
  # check the poles
  if (is.null(poles)) {
    stop("polarity is not set for this dictionary; see ?polarity",
         call. = FALSE)
  }
  check_that_poles_exist(dictionary, poles)
```
and we generate this error on the first line 
```
  poles <- polarity(dictionary)
```

So your code doesn't reach the is.null call in the code.

Please fix it

**Comment by AOurednikSFA** [comment]
Getting a similar error here. R version 4.0.2 , quanteda 3.0.0

```
Warning message:
Not a validObject(): no slot of name "meta" for this object of class "dictionary2" 
```
Somehow the dictionary2 object has trouble sticking in memory
A similar error message arises when saving R session to memory with `save.image`. Quanteda DFM objects are not reloaded with `load`

**Comment by kbenoit** [comment]
Updating your packages should fix this now.
